# Generated by Django 5.0.1 on 2024-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
